version: '3'

services:
  traefik:
    container_name: traefik
    build:
      context: ./traefik
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    container_name: api
    depends_on:
      - traefik
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.routers.api.entrypoints=web
