version: '3'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./webapp:/app
    environment:
      - CHOKIDAR_USEPOLLING=1
    ports:
      - '35729:35729'

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    volumes:
      - ./api:/app
