version: '3'

services:
  traefik:
    container_name: traefik
    build:
      context: ./traefik
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    container_name: api
    depends_on:
      - traefik
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.routers.api.entrypoints=web
    environment:
      - DB_URI=db+mysql://generator:password123@db:3306/generator

  worker:
    container_name: worker
    depends_on:
      - traefik
    environment:
      - DB_URI=db+mysql://generator:password123@db:3306/generator
      - BROKER_URI=redis://password123@redis:6379/0

  redis:
    container_name: redis
    image: redis:6.2.1-alpine
    depends_on:
      - traefik
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123

  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=generator
      - MYSQL_PASSWORD=password123
      - MYSQL_USER=generator
      - MYSQL_TCP_PORT=3306
