version: '3'

services:
  webapp:
    container_name: webapp
    depends_on:
      - traefik
    build:
      context: ./webapp
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./webapp:/app
    environment:
      - CHOKIDAR_USEPOLLING=1
    ports:
      - 5000
      - 35729:35729
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`localhost`)
      - traefik.http.routers.webapp.entrypoints=web

  api:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/app:/app
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--reload', '--port', '80']

  worker:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/app:/app
    command: ['celery', '-A', 'worker.celery', 'worker']
